env:
  global:
  - secure: PavryfczFWvhCn9SqF+f0gloihPFjxQprs80F2473aX/AdMiiaL4rRedSyKdVvJWfiuEw//1onaeGdwyucEe05ervkou9hu2wmRkT5EWsoqGAKa4PbGkEhqWKj0n3Byw2vKH+Z4Mie8Y5/tTGT6NyPs1r6KeEzb3kmLMwOTchHk=
  - secure: NIzzLPSpy8dAvppP1Zj4LEcOBrL642IoERozg/2qII9y9tUeousKJi5DbEvePK3uUVfkgTvDatElgpZWvNYIEdLwhasLMf7mVisC4EVDZlpD9aG0E53s3gle30iuFgRgr05yiA7DwBLxFjM7QqvWkn7XH2wU109fwXvP1xBfZbo=
  - TO=production
  - REVISION=$(git rev-parse HEAD)
  - REPO=waxpoeticrecords.com
  - DISPLAY:=99.0
  - FORMAT=documentation
  - COVERAGE=false
branches:
  only:
    - master
language: ruby
rvm: 2.0.0-p247
bundler_args: --without=development
before_script: bundle exec rake db db:migrate db:test:prepare
script: bundle exec rake test
after_script: bundle exec rake deploy
