env:
  global:
  - TO=production
  - REVISION=$(git rev-parse HEAD)
  - REPO=waxpoeticrecords.com
  - USER=tubbo
  - secure: XYOwwmp3+Df9j9ATSq1nLs7z02DhhiqT6JjYFzzhZ9NeAqx/+zSp2PMcMN9bqw5oLZdpzRTkhTvzw2TjwyghA19ppo1f3RxPFH9HrZS+P5i0CgS7Z0dSf9OXz/3SK4W3K/pROski+OldUJWiTgo6YeocN4Ijj8zYI1la5EB032Q=
branches:
  only:
  - master
  - store
language: ruby
rvm: 2.0.0
bundler_args: --without=development
before_script: bundle exec rake db db:migrate
script: bundle exec rake test
after_success: RAILS_ENV=production bundle exec rake airbrake:deploy
deploy:
  provider: heroku
  api_key:
    secure: fsu7TexuJ9dG5wQO6oEJ5UfKPYFJcxZhPQZF7XIuze8Af1YH4MhB1hkmp7xfpIGC6vAJcD786XdpAjO5uzZEEgHXG1gpkeVeAFubLjgZz0OMAPMUhkKXaQR8WWxOFmoHJoQAsfaBUxzOaUXpF+76RCklyYLH0BtIkxOKPLqkxIw=
  app: waxpoetic
  on:
    repo: waxpoetic/waxpoeticrecords.com
