env:
  global:
  - TO=production
  - REVISION=$(git rev-parse HEAD)
  - REPO=waxpoeticrecords.com
  - RAILS_SECRET='hello-i-am-running-on-travis-ci'
branches:
  only:
  - master
  - store
language: ruby
rvm: 2.0.0
bundler_args: --without=development
before_script: bundle exec rake db
script: bundle exec rake test
deploy:
  provider: heroku
  api_key:
    secure: fsu7TexuJ9dG5wQO6oEJ5UfKPYFJcxZhPQZF7XIuze8Af1YH4MhB1hkmp7xfpIGC6vAJcD786XdpAjO5uzZEEgHXG1gpkeVeAFubLjgZz0OMAPMUhkKXaQR8WWxOFmoHJoQAsfaBUxzOaUXpF+76RCklyYLH0BtIkxOKPLqkxIw=
  app: waxpoetic
  on:
    repo: waxpoetic/waxpoeticrecords.com
