env:
  global:
  - secure: PavryfczFWvhCn9SqF+f0gloihPFjxQprs80F2473aX/AdMiiaL4rRedSyKdVvJWfiuEw//1onaeGdwyucEe05ervkou9hu2wmRkT5EWsoqGAKa4PbGkEhqWKj0n3Byw2vKH+Z4Mie8Y5/tTGT6NyPs1r6KeEzb3kmLMwOTchHk=
  - secure: NIzzLPSpy8dAvppP1Zj4LEcOBrL642IoERozg/2qII9y9tUeousKJi5DbEvePK3uUVfkgTvDatElgpZWvNYIEdLwhasLMf7mVisC4EVDZlpD9aG0E53s3gle30iuFgRgr05yiA7DwBLxFjM7QqvWkn7XH2wU109fwXvP1xBfZbo=
  - TO=production
  - REVISION=$(git rev-parse HEAD)
  - REPO=waxpoeticrecords.com
branches:
  only:
    - master
    - store
language: ruby
rvm: 2.0.0
bundler_args: --without=development
before_script:
  - bundle exec rake db
  - bundle exec rake db:test:prepare
script: bundle exec rake db:migrate test
after_script: bundle exec rake deploy
